added pause menu + fixed wall slide bug
GameProgrammingCapstoneProject/CapstoneProject pull request #119
Opened 2024-02-14 23:48 UTC by Joshua12450

2024-02-15 13:41 UTC, Betadrone approved these changes

2024-02-15 13:58 UTC, NoahMKuzyk requested changes
Attach script to pause object, update prefab

2024-02-15 16:47 UTC, NoahMKuzyk approved these changes
Approved
Note: Minor bug with menu, first frame of animation plays if input is given while paused
Fix later

2024-02-15 16:47 UTC, merged

2024-02-28 19:51 UTC, DoopweeSLC commented on CapstoneProject/Assets/Scripts/Core/Controller/PlayerController.cs
> +                }
this can be simplified to PauseMenu.isPause = !PauseMenu.isPause;