Save and load improvements
GameProgrammingCapstoneProject/CapstoneProject pull request #189
Opened 2024-03-14 13:50 UTC by Joshua12450

2024-03-14 14:51 UTC, NoahMKuzyk requested changes
Interacting with shopkeeper softlocks the player

2024-03-14 15:51 UTC, Betadrone approved these changes

2024-03-14 15:54 UTC, merged

2024-03-16 20:24 UTC, DoopweeSLC commented on CapstoneProject/Assets/Scripts/Core/Components/Characters/Playable_Character/PlayerAbilityComponent.cs
> +            case 1:
should make an enum for these cases for each ability type

2024-03-16 20:24 UTC, DoopweeSLC commented on CapstoneProject/Assets/Scripts/Core/Components/Characters/Playable_Character/PlayerAbilityComponent.cs
> +        switch (abilitytwo)
should we just make a function for this switch to save from it being duplicated? takes in the ability as one param and the ability to set as the other?

2024-03-16 20:24 UTC, DoopweeSLC commented on CapstoneProject/Assets/Scripts/Core/Entity/Characters/Playable_Character/Player.cs
> +                switch (data.playerAbilityOne)
same here, could be a function