Fix chest opening bug
GameProgrammingCapstoneProject/CapstoneProject pull request #251
Opened 2024-03-28 03:45 UTC by thienphuochoang

2024-03-28 12:42 UTC, Kanika834 approved these changes

2024-03-28 12:59 UTC, NoahMKuzyk requested changes
Remove Main Menu.cs from commit; accident

2024-03-28 13:23 UTC, Betadrone approved these changes

2024-03-28 13:29 UTC, NoahMKuzyk approved these changes
Fixed, thx

2024-03-28 13:29 UTC, merged

2024-04-09 15:15 UTC, DoopweeSLC commented on CapstoneProject/Assets/Scripts/Core/Entity/Objects/Item.cs
> +            _player.GetComponent<KeyItemComponent>().TryToUseKeys();
try use keys returns a bool. if they don't have a key right now you still give them the coins and open? but if they have a key you take it away?

2024-04-09 15:16 UTC, DoopweeSLC commented on CapstoneProject/Assets/Scripts/Core/Entity/Objects/Item.cs
> +            _player.GetComponent<KeyItemComponent>().TryToUseKeys();
I see you do this above in your check though, so if they have 2 keys, you'd use both on the one chest :(