Falling platform
GameProgrammingCapstoneProject/CapstoneProject pull request #252
Opened 2024-03-28 06:02 UTC by thienphuochoang

2024-03-28 12:42 UTC, Kanika834 approved these changes

2024-03-28 13:00 UTC, NoahMKuzyk requested changes
Same issue as other branch; accidentally added other changed files from scripts

2024-03-28 13:31 UTC, Betadrone approved these changes

2024-03-28 13:32 UTC, merged

2024-04-09 15:21 UTC, DoopweeSLC commented on CapstoneProject/Assets/Scripts/Core/Puzzle/FallingPlatform.cs
> +                gameObject.GetComponent<Rigidbody2D>().bodyType = RigidbodyType2D.Dynamic;
you do this getcomponent about 7 times in this file, might be worth caching