added scene checking to music manager
GameProgrammingCapstoneProject/CapstoneProject pull request #300
Opened 2024-04-10 23:17 UTC by Joshua12450

it'll adjust what song is playing and what the music slider will do based on the song playing, please do not approve until both noah and thein have approved

2024-04-10 23:42 UTC, Betadrone approved these changes

2024-04-11 12:45 UTC, NoahMKuzyk requested changes
Non-functional, plz fix

2024-04-11 13:51 UTC, CharaKK requested changes
Still doesn't work as is...

2024-04-11 14:18 UTC, NoahMKuzyk approved these changes

2024-04-11 14:19 UTC, merged

2024-04-20 23:04 UTC, DoopweeSLC commented on CapstoneProject/Assets/Scripts/Core/Audio/SoundManager.cs
> +            s.source.volume = (s.volume * musicMod);
this is done in all ifs, maybe just do it once below them all?

2024-04-20 23:04 UTC, DoopweeSLC commented on CapstoneProject/Assets/Scripts/Core/Audio/SoundManager.cs
> +            s.source.volume = (s.volume * musicMod);
this would actually cause a bug where changing the volume within the main menu would not change the volume