Behavior tree viewer UI
GameProgrammingCapstoneProject/CapstoneProject pull request #69
Opened 2024-01-31 20:26 UTC by Betadrone

2024-01-31 21:15 UTC, thienphuochoang requested changes
Fixed the bug in the Update function

2024-01-31 21:21 UTC, thienphuochoang approved these changes

2024-01-31 22:00 UTC, Kanika834 approved these changes

2024-01-31 22:01 UTC, merged

2024-02-18 00:25 UTC, DoopweeSLC commented on CapstoneProject/Assets/Scripts/Core/BehaviorTree/CoreNodeTypes/CompositeNode.cs
> +        return node;
Maybe I'm not understanding correctly the functionality here, but this function seems like it is recursively going to keep cloning children? Does this not create too many children though as each child would keep making more instances?